### ISSUE TITLE
Create CONTRIBUTING.md Document

### ISSUE THREAD

**Issue by wvdk** [wvdk/Life-Calendar#5]
## About
- https://github.com/blog/1184-contributing-guidelines

## Examples
- https://github.com/puppetlabs/puppet/blob/master/CONTRIBUTING.md
- https://github.com/thoughtbot/factory_girl_rails/blob/master/CONTRIBUTING.md
- https://github.com/CodeDoesGood/iOS-Template/blob/master/README.md

## Todo
- [x] Move stuff from https://github.com/wvdk/Life-Calendar/wiki/Branching-and-submitting-pull-requests into Markdown document
- [x] Disable Wiki in this github project
- [ ] Read the links above

**Comment by wvdk** [comment]
Branch name: `Issue-5-Create-CONTRIBUTING-Document`
